// <auto-generated>
//   Generated by build/gen_native_methods.py from native/include/prismpdf.h.
//   Do not edit by hand: vendor a newer header, then regenerate and review the diff.
// </auto-generated>
//
// The raw layer. Binding author's guide, "Architecture: two layers, always":
//   "one flat, mechanical, 1:1 projection of prismpdf.h. No logic, no renaming beyond the
//    language's FFI syntax."
//
// Three projections are worth knowing, because they are the only places C# cannot say what
// C says:
//   * C `bool` (one byte) becomes `byte`. Zero is false, non-zero is true.
//   * Every opaque `PrismPdf… *` handle becomes `nint`, and `PrismPdf… **` becomes `nint*`.
//   * `char *` and `uint8_t *` become raw `byte*`. Strings are never auto-marshalled: an
//     owned `char **` out-param must be copied and then released with prismpdf_string_free,
//     which no built-in marshaller knows how to do.
//
// Declarations are [DllImport], not [LibraryImport]: this SDK targets netstandard2.0, and
// the LibraryImport source generator requires .NET 7+. The projection is otherwise identical
// — cdecl is pinned on the attribute rather than by [UnmanagedCallConv], and ExactSpelling
// stops the runtime probing for A/W suffixed variants that the C ABI does not have.
//
// Ownership is NOT enforced here. It is enforced exactly once, in the idiomatic layer.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace PrismPdf.Interop;

/// <summary>
/// Direct P/Invoke declarations for the Prism PDF C ABI. Internal by design: the ownership and
/// error conventions live in the idiomatic layer, and user code must not be able to bypass
/// them.
/// </summary>
internal static unsafe class NativeMethods
{
    /// <summary>
    /// The native artifact name. The loader resolves it to <c>libpdf_ffi.dylib</c> (macOS),
    /// <c>libpdf_ffi.so</c> (Linux) or <c>pdf_ffi.dll</c> (Windows). Not to be confused with
    /// <c>prismpdf</c>, which is the CLI binary.
    /// </summary>
    internal const string Library = "pdf_ffi";

    [ModuleInitializer]
    internal static void Initialize() => NativeLibraryResolver.Register();

    // ---------------------------------------------------------------------------------------
    // Structured failure diagnostics
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_last_error(nint* out_error);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_error_info_status(nint error, PrismPdfStatus* out_status);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_error_info_message(nint error, byte** out_message);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_error_info_free(nint error);

    // ---------------------------------------------------------------------------------------
    // Library-level: version and the two deallocators
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern byte* prismpdf_version();

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_string_free(byte* text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_bytes_free(byte* data, nuint len);

    // ---------------------------------------------------------------------------------------
    // Open and lifecycle
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_open(byte* data, nuint len, nint* out_doc);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_open_with_password(byte* data, nuint len, byte* password, nuint password_len, nint* out_doc);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_open_with_options(byte* data, nuint len, nint options, nint* out_doc);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_open_with_limits(byte* data, nuint len, PrismPdfLimits* limits, nint* out_doc);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_open_with_private_key(byte* data, nuint len, byte* cert_der, nuint cert_len, byte* key_der, nuint key_len, nint* out_doc);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_document_free(nint doc);

    // ---------------------------------------------------------------------------------------
    // Open options (the ABI-extensible replacement for PrismPdfLimits)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint prismpdf_open_options_new();

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_open_options_set_max_depth(nint options, nuint max_depth);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_open_options_set_max_objstm_objects(nint options, nuint max_objects);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_open_options_set_max_objects(nint options, nuint max_objects);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_open_options_set_password(nint options, byte* password, nuint password_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_open_options_free(nint options);

    // ---------------------------------------------------------------------------------------
    // Open report: strict versus recovered
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_open_report(nint doc, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_open_report_mode(nint report, OpenMode* out_mode);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_open_report_diagnostic_count(nint report, nuint* out_count);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_open_report_diagnostic(nint report, nuint index, RecoveryReason* out_reason, byte* out_has_offset, nuint* out_offset);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_open_report_free(nint report);

    // ---------------------------------------------------------------------------------------
    // Read path
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_page_count(nint doc, nuint* out_count);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_version(nint doc, byte* out_major, byte* out_minor);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_min_version(nint doc, byte* out_major, byte* out_minor);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_page_text(nint doc, nuint index, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_page_text_positioned(nint doc, nuint index, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_text(nint doc, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_xmp(nint doc, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_info(nint doc, byte* key, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_creation_date(nint doc, PrismPdfDate* out_date);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_modification_date(nint doc, PrismPdfDate* out_date);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_structure_namespaces(nint doc, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_signature_vri_keys(nint doc, nint* out_list);

    // ---------------------------------------------------------------------------------------
    // Write and transform
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save(nint doc, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_report(nint doc, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_compact(nint doc, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_compact_report(nint doc, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_packed(nint doc, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_packed_report(nint doc, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_as(nint doc, byte major, byte minor, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_as_report(nint doc, byte major, byte minor, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_extract_pages(nint doc, nuint* indices, nuint count, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_extract_pages_report(nint doc, nuint* indices, nuint count, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_rotate_page(nint doc, nuint index, long degrees, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_rotate_page_report(nint doc, nuint index, long degrees, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_subset_fonts(nint doc, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_subset_fonts_report(nint doc, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_merge(nint* docs, nuint count, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_merge_report(nint* docs, nuint count, nint* out_report);

    // ---------------------------------------------------------------------------------------
    // Transform report
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_transform_report_bytes(nint report, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_transform_report_rewrite_mode(nint report, RewriteMode* out_mode);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_transform_report_signature_effect(nint report, SignatureEffect* out_effect);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_transform_report_structure_effect(nint report, StructureEffect* out_effect);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_transform_report_free(nint report);

    // ---------------------------------------------------------------------------------------
    // Annotations (12.5)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_page_annotations(nint doc, nuint index, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_annotation_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_annotation_list_get(nint list, nuint index, nint* out_item);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_annotation_list_free(nint list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_annotation_subtype(nint annot, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_annotation_rect(nint annot, double* out_rect);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_annotation_contents(nint annot, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_annotation_uri(nint annot, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_annotation_dest_page(nint annot, nuint* out_index);

    // ---------------------------------------------------------------------------------------
    // Interactive forms (12.7)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_form_fields(nint doc, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_form_field_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_form_field_list_get(nint list, nuint index, nint* out_item);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_form_field_list_free(nint list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_form_field_name(nint field, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_form_field_type(nint field, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_form_field_value(nint field, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_fill_form(nint doc, byte** names, byte** values, nuint count, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_fill_form_report(nint doc, byte** names, byte** values, nuint count, nint* out_report);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_flatten_form(nint doc, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_flatten_form_report(nint doc, nint* out_report);

    // ---------------------------------------------------------------------------------------
    // Outline / bookmarks (12.3.3)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_outline(nint doc, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_outline_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_outline_list_get(nint list, nuint index, nint* out_item);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_outline_list_free(nint list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_outline_item_title(nint item, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_outline_item_dest_page(nint item, nuint* out_index);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_outline_item_child_count(nint item, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_outline_item_child(nint item, nuint index, nint* out_child);

    // ---------------------------------------------------------------------------------------
    // Embedded files (7.11)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_attachments(nint doc, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_attachment_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_attachment_list_get(nint list, nuint index, nint* out_item);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_attachment_list_free(nint list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_attachment_name(nint att, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_attachment_data(nint att, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_attachment_mime(nint att, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_attachment_relationship(nint att, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_attachment_description(nint att, byte** out_text);

    // ---------------------------------------------------------------------------------------
    // Fonts (9.5-9.7, 9.9)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_fonts(nint doc, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_list_get(nint list, nuint index, nint* out_item);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_font_list_free(nint list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_base_font(nint font, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_subtype(nint font, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_program_format(nint font, FontFormat* out_format);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_program(nint font, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_metrics(nint font, ushort* out_units_per_em, ushort* out_glyph_count);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_font_family_name(nint font, byte** out_text);

    // ---------------------------------------------------------------------------------------
    // Images (8.6, 8.9)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_page_images(nint doc, nuint index, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_image_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_image_list_get(nint list, nuint index, nint* out_item);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_image_list_free(nint list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_image_info(nint image, uint* out_width, uint* out_height, byte* out_bits_per_component);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_image_color_space(nint image, ColorSpace* out_space);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_image_components(nint image, byte* out_components);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_image_kind(nint image, ImageKind* out_kind);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_image_data(nint image, byte** out_data, nuint* out_len);

    // ---------------------------------------------------------------------------------------
    // String lists
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_string_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_string_list_get(nint list, nuint index, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_string_list_free(nint list);

    // ---------------------------------------------------------------------------------------
    // Access permissions (7.6.3.2)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_restricted();

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_all();

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_print(int permissions);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_modify(int permissions);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_copy(int permissions);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_annotate(int permissions);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_fill_forms(int permissions);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_accessibility(int permissions);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_assemble(int permissions);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern int prismpdf_permissions_allow_print_high_res(int permissions);

    // ---------------------------------------------------------------------------------------
    // Encryption (7.6)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_encrypted(nint doc, byte* user_password, nuint user_len, byte* owner_password, nuint owner_len, uint algorithm, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_encrypted_with(nint doc, byte* user_password, nuint user_len, byte* owner_password, nuint owner_len, int permissions, byte encrypt_metadata, uint algorithm, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_encrypted_public_key(nint doc, byte** certs, nuint* cert_lens, nuint count, int permissions, byte encrypt_metadata, uint algorithm, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_save_encrypted_with_mac(nint doc, byte* user_password, nuint user_len, byte* owner_password, nuint owner_len, int permissions, byte encrypt_metadata, uint algorithm, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_verify_pdf_mac(nint doc, byte* password, nuint password_len, byte* out_valid);

    // ---------------------------------------------------------------------------------------
    // Signing (12.8)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint prismpdf_sign_settings_new();

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_sign_settings_free(nint settings);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_name(nint settings, byte* name);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_reason(nint settings, byte* reason);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_location(nint settings, byte* location);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_contact_info(nint settings, byte* contact);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_signing_time(nint settings, ulong unix_time);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_pades(nint settings, byte pades);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_appearance(nint settings, nuint page_index, float* rect, byte* text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_sign_settings_set_timestamp(nint settings, byte* cert_der, nuint cert_len, byte* key_der, nuint key_len, ulong gen_time, ulong serial);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_sign(nint doc, byte* cert_der, nuint cert_len, byte* key_der, nuint key_len, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_sign_with(nint doc, byte* cert_der, nuint cert_len, byte* key_der, nuint key_len, nint settings, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_sign_with_mac(nint doc, byte* cert_der, nuint cert_len, byte* key_der, nuint key_len, nint settings, byte* password, nuint password_len, byte** out_data, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_timestamp(nint doc, byte* tsa_cert_der, nuint cert_len, byte* tsa_key_der, nuint key_len, ulong gen_time, byte has_gen_time, byte** out_data, nuint* out_len);

    // ---------------------------------------------------------------------------------------
    // Verification (12.8, 12.8.4)
    // ---------------------------------------------------------------------------------------

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_verify_signatures(nint doc, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_verify_signatures_with(nint doc, byte** roots, nuint* root_lens, nuint count, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_document_verify_signatures_ltv(nint doc, byte** roots, nuint* root_lens, nuint count, nint* out_list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_list_len(nint list, nuint* out_len);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_list_get(nint list, nuint index, nint* out_item);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void prismpdf_signature_list_free(nint list);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_valid(nint sig, byte* out_valid);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_signer(nint sig, byte** out_text);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_covered_bytes(nint sig, nuint* out_bytes);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_signing_time(nint sig, long* out_time);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_timestamp_time(nint sig, long* out_time);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_trusted(nint sig, byte* out_trusted);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_pades(nint sig, byte* out_pades);

    [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern PrismPdfStatus prismpdf_signature_revocation(nint sig, Revocation* out_revocation);
}
